#!/bin/bash

set -o errexit

bindir=${BINDIR:-$(dirname $0)/../bin}
timeCmd=${TIME:-"/usr/bin/time -v"}

input=$(echo $1 | sed 's/[\._]nc$//')
name=$(basename $input)
shift 1

if [[ $name =~ ^segmented ]]
then
  echo "=== SignedEuclideanDistanceTransform ==="
  scalars=$(echo $name | sed 's/^segmented/tomo_float/')_SEDT
  $timeCmd $bindir/SEDT ${input}[._]nc ${scalars}.nc
else
  scalars=$input
fi

output=$(basename $scalars | sed 's/^tomo_float/vector_field/')_GVF_SMP

echo "=== VectorField ==="
$timeCmd $bindir/VectorField ${scalars}[._]nc __field.nc
echo '=== Simplify ==='
$timeCmd $bindir/Simplify ${scalars}[._]nc __field[._]nc ${output}.nc $*

rm -rf __*
